language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- "./ci/bin/build.sh"
- "./ci/bin/test.sh"
- "./ci/bin/cover.sh"
- "./ci/bin/report.sh"
env:
  global:
    secure: DrjVdg/fYLLR48LQP3oyR5y72BHUVxtjVqjF0RwT7qHNDSbv123/TiQMq0qdTtWKACiRjmMyVqII6CGqwjbSvZgH/ZrEna6LAZtx6EutVILaq8NOa6261WDN8uKX/X6j8ADoE8XZ4EvtMMt6DrEPy3fC5nYLdv5XIotImN3L5IdnSz6IOE5qoVrbiD/zdf5Gr8lAKbCSNRTiNx0OkpT6dpqp3qPxiLPtleokq7e15gLSKsQCCdR5dlNBjc2RpMI9De/8rcrhMQuVmfIOo3zBDJmUu7FUVdgUQXnYAaCaU/1/wWpAvsNEUy7hlguzTXCXZJAIR6pUiqwyAI0K1nwq+kfuU0k4+FRj6Aq57Zyfnf2qFp35ann/DpqH2KzFfGO7ZgbJl1ZGW9iyh2z7f/J8gR5elR+0GgXwNH19aD+NZ1fOdZAL4S6R8IsFfusEFhIWp3Ow86O9az93AdCoLoSvhwfrert0kKAuJY+9W5wJBszCvzLWq304NgOeaJrjKqg6Apmv0YaU6+B4lClYXX3UDXIzZsYC5ymyzNF2AWGFYtLMH11Xs7iTtv5NPe0hdOsVodQ47dpSHp/PXEkHDGOscYq/WybVNgNDvcLqcdbLS9Q9pLcGMzmQt0QGtA/iIg73MdSLvIV5BqKWsDCptmPWCvu6gARC+jfe9nH4dfQkrss=
