language: node_js
node_js:
- '5.0'
before_install: 
- npm -g install mocha nodeunit istanbul
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
